"""job runs

Revision ID: 1598859b12f5
Revises: dc823681caea
Create Date: 2026-08-01 11:36:59.963708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1598859b12f5'
down_revision: Union[str, None] = 'dc823681caea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'day', name='uq_job_day')
    )
    # ### end Alembic commands ###

    # Provider tokens used to be stored in the clear. Encrypt whatever is already
    # there. `decrypt` returns None for anything that isn't Fernet ciphertext, which
    # makes this both the detector and the guard against double-encrypting on a re-run.
    from app.crypto import decrypt, encrypt

    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SELECT id, access_token, refresh_token FROM provider_connections")
    ).fetchall()
    for row_id, access, refresh in rows:
        if decrypt(access) is not None:
            continue
        bind.execute(
            sa.text(
                "UPDATE provider_connections SET access_token = :a, refresh_token = :r"
                " WHERE id = :i"
            ),
            {"a": encrypt(access), "r": encrypt(refresh), "i": row_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_runs')
    # ### end Alembic commands ###
